# Generated by Django 4.0.5 on 2022-12-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(max_length=150)),
                ('book_name', models.CharField(max_length=150)),
                ('book_category', models.CharField(choices=[('READER', 'READER'), ('STORY', 'STORY'), ('POETRY', 'POETRY')], max_length=6)),
                ('book_content', models.TextField(max_length=150)),
                ('published_by', models.CharField(max_length=150)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
