# Generated by Django 4.0.5 on 2022-12-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybook',
            name='book_image',
            field=models.ImageField(null=True, upload_to='bookimages'),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='book_content',
            field=models.TextField(),
        ),
    ]
